### PR TITLE
Add submission file related info

### PR DESCRIPTION
**Pull request by Adman**
Signed-off-by: Adrian Matejov <ado.matejov@gmail.com>

Copying "Code submission" and "Submission check" pages from rcj-soccer-sim repository.
We should decide whether we are going to use different folder structure than `robot/robot.py`

### CODE REVIEW

**Comment by Adman** [comment]
I changed the `robot/robot.py` to `rcj_soccer_team_blue/rcj_soccer_team_blue.py`. Any comments are welcome.

**Comment by mrshu** [comment]
Sorry @Adman, I totally panicked out in here.

What do you think would be the next best step? I am happy for the existing `code-submission.md` to simply go away :)

**Comment by Adman** [comment]
@mrshu Did you copy the `code-submission.md` file from previous page? If so, I can remove it from the PR

**Comment by mrshu** [comment]
@Adman moreless, yeah. Would you mind reading through it and updating anything worth changing form your point of view?

Thanks!

**Comment by Adman** [comment]
@mrshu Yes, will do.

**Comment by Adman** [comment]
@mrshu I removed `code-submission.md` from the PR.

**Comment by mrshu** [comment]
Thanks @Adman. I am wondering where should this JS file reside after all (copying it over is really counter-productive but perhaps the best thing we have for now).

In generally, don't be afraid to get this merged :)

**Comment by Adman** [comment]
@mrshu Yeah, we could maybe host the file somewhere and include it from there. Merging for now.

**Pull request merged**
